# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=b'title')),
                ('slug', models.SlugField(unique=True, verbose_name=b'slug')),
            ],
            options={
                'ordering': ('title',),
                'db_table': 'categories',
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('project_url', models.URLField(verbose_name=b'Project URL')),
                ('description', models.TextField(blank=True)),
                ('completion_date', models.DateField()),
                ('in_development', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, upload_to=b'images/portfolio')),
                ('is_featured', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Client')),
                ('type', models.ManyToManyField(blank=True, to='portfolio.Category')),
            ],
            options={
                'ordering': ('-completion_date',),
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image_path', models.CharField(blank=True, max_length=100)),
                ('image', models.FileField(blank=True, upload_to=b'images/portfolio')),
                ('credit', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(verbose_name=b'Is this image featured on your main pages?')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_images',
            },
        ),
    ]
